# /Users/alex/.config/tmuxinator/config.yml

name: config
root: ~/projects/dotfiles

windows:
  - editor:
      layout: main-vertical
      panes:
        -
  - nvim:
      layout: main-vertical
      panes:
        - cd nvim
  - tmux:
      layout: main-vertical
      panes:
        - cd tmux
