export PATH=$HOME/bin:/usr/local/bin:$PATH

export ZSH="/root/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git)

source $ZSH/oh-my-zsh.sh

alias vim='nvim'
alias vimconf='vim ~/.dotfiles/vim/vimrc'
alias zshconf="vim ~/.zshrc"
alias bashconf='vim ~/.dotfiles/bash/bashrc'
alias tmuxconf='vim ~/.dotfiles/tmux/tmux.conf'
alias reload='source ~/.dotfiles/zsh/zshrc'
alias dotfiles='cd ~/.dotfiles'
alias me='cd ~/projects'

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# tmux attach setup
alias mux='tmux new-session -ADs main'

# tmux detach setup
exit() {
  if [[ -z $TMUX ]]; then
    builtin exit
    return
  fi

  panes=$(tmux list-panes | wc -l)
  wins=$(tmux list-windows | wc -l)
  count=$(($panes + $wins - 1))
  if [ $count -eq 1 ]; then
    tmux detach
  else
    builtin exit
  fi
}

# csv viewer
csview() {
  local file="$1"
  cat "$file" | sed 's/,/ ,/g' | column -t -s, | less -S
}
