# Set the shell to zsh
export SHELL=/usr/local/bin/zsh
export LANG=en_US.UTF8
export LC_ALL=en_US.UTF-8

# Import locations
export ZSH_CUSTOM=~/.config/zsh/custom/
export ZSH_ENV_HOME=$HOME/
export XDG_CONFIG_HOME=$HOME/.config
export PATH="$HOME/.local/bin/:$PATH"

# ZSH options
setopt emacs
setopt functionargzero
setopt hist_ignore_space

export HISTSIZE=100000000
export SAVEHIST=$HISTSIZE
export HISTFILE=$HOME/.local/zsh_history

# Plugins
source $XDG_CONFIG_HOME/antigen/antigen.zsh

antigen bundle 'zsh-users/zsh-syntax-highlighting'
antigen bundle 'zsh-users/zsh-autosuggestions'

antigen apply

# Key bindings
bindkey '^n' autosuggest-accept

# starship prompt
eval "$(starship init zsh)"

# My "Plugins"
sources=()

for s in "${sources[@]}"; do
  source $HOME/.config/zsh/include/${s}.zsh
done

alias vim='nvim'
alias reload='source ~/.zshrc'
alias cleanup='fd --no-ignore --hidden .DS_Store . | xargs rm'
alias dotconf='cd ~/projects/dotfiles; vim'
alias vimconf='vim ~/projects/dotfiles/nvim/init.lua'
alias zshconf='vim ~/projects/dotfiles/zsh/zshrc'
alias yaconf='vim ~/projects/dotfiles/yabai/yabairc'
alias bashconf='vim ~/projects/dotfiles/bash/bashrc'
alias tmuxconf='vim ~/projects/dotfiles/tmux/tmux.conf'
alias tn='tmuxinator n'
alias to='tmuxinator o'
alias ts='tmuxinator s'
alias pm='pnpm'
alias cpwd="pwd | tr -d '\n' | pbcopy && echo 'pwd copied to clipboard'"
alias alacritty='/Applications/Alacritty.app/Contents/MacOS/alacritty'
alias wf=workfile
alias wd=workdir
alias wt=worktree

# Tree
alias tree='tree -CIa "node_modules|.git|.cache|.next|.turbo" --dirsfirst'
alias t1='tree -L 1 -CIa "node_modules|.git|.cache|.next|.turbo" --dirsfirst'
alias t2='tree -L 2 -CIa "node_modules|.git|.cache|.next|.turbo" --dirsfirst'
alias t3='tree -L 3 -CIa "node_modules|.git|.cache|.next|.turbo" --dirsfirst'

# ls
alias ls="gls --group-directories-first --color=auto"
alias la="gls -la --group-directories-first --color=auto"
alias ll="gls -l --group-directories-first --color=auto"

# quickly jump to workdir
#
# Usecases:
#
# workdir <pattern>
# workdir

function workdir() {
  local result=""

  if [ $# -gt 1 ] && echo "Too many agruments" && return

  if [ $# -gt 0 ]; then
    result=$(fd --type directory $1 ~/projects)
  else
    result=$(fd --type directory . ~/projects)
  fi

  # validate fd command before pipe to fzy
  if [ -z "$result" ] && echo "No directory match query: $1" && return

  # validate fzy selection before next execution
  local selection=$(echo $result | fzy)
  if [ -z "$selection" ] && return

  cd $(echo $selection)
}

# quickly change to worktree
#
# Usecases:
#
# worktree <pattern>
# worktree

function worktree() {
  local result=$(git worktree list)

  # validate fd command before pipe to fzy
  if [ -z "$result" ] && echo "No directory match query: $1" && return

  # validate fzy selection before next execution
  local selection=$(echo $result | fzy)
  if [ -z "$selection" ] && return

  # cd to target directory
  local target=$(echo $selection | awk '{print $1}')
  cd $target
}

# NPM
alias nr="npm run"
alias np="npm version patch && npm publish && git push origin master --tags"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# csv viewer
csview() {
  local file="$1"
  cat "$file" | sed 's/,/ ,/g' | column -t -s, | less -S
}

# shopify env
source $HOME/projects/dotfiles/shopify_alias.sh
alias theme='shopify theme'

# bun completions
[ -s "/Users/alex/.bun/_bun" ] && source "/Users/alex/.bun/_bun"

# Bun
export BUN_INSTALL="/Users/alex/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# pnpm
export PNPM_HOME="/Users/alex/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end
