# vim: ft=zsh
unsetopt  correct    # Correct spelling for commands
unsetopt  correctall # turn off the infernal correctall for filenames

# Changing directories
setopt    auto_cd
setopt    auto_pushd
setopt    pushd_ignore_dups
setopt    pushd_minus

# Expansion and globbing
setopt    glob
unsetopt  case_glob
unsetopt  case_match

# Emacs key bindings (use -v for vi key bindings)
bindkey -e

# Base PATH
export PATH="$PATH:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin"

# Default editor
export EDITOR='nvim'

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export XDG_CONFIG_HOME="$HOME/.config"

# Prevent duplicate entries
typeset -U path
typeset -U fpath

# ZPLUG setup
export ZPLUG_HOME=/usr/local/opt/zplug
source $ZPLUG_HOME/init.zsh

zplug "plugins/git", from:oh-my-zsh
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-completions"
zplug mafredri/zsh-async, from:github
zplug sindresorhus/pure, use:pure.zsh, from:github, as:theme

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi
zplug load

# Lazydocker
alias lzd='lazydocker'

# Nodenv
eval "$(nodenv init -)"

# Postgres setup
export PATH="/usr/local/opt/libpq/bin:$PATH"

# FZF bootstrap
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# Functions
# Easy npm publish
publish() {
  npm version "$1" && git push origin master --tags && npm publish
}

# Local IP
localip() {
  ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk "{print $2}"
}

# Better tree lists
tt() {
    tree -I ".git|.node_modules|.DS_Store" --dirsfirst --filelimit 15 -L ${1:-3} -aC $2
}

# fkill - kill process
fkill() {
  local pid
  pid=$(ps -ef | sed 1d | fzf -m | awk "{print $2}")

  if [ "x$pid" != "x" ]
  then
    echo $pid | xargs kill -${1:-9}
  fi
}

# Tmux
if [ -z "$TMUX" ]
then
    tmux attach -t TMUX || tmux new -s TMUX
fi

# Aliases
# Safety first
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"
alias del="mv -t ~/.Trash/"
alias vim="nvim"

# cd
alias .2="cd ../.."
alias .3="cd ../../.."
alias .4="cd ../../../.."
alias .5="cd ../../../../.."
alias .6="cd ../../../../../.."

# zsh
alias reload="source ~/.zshrc"

# fs
export EXA_COLORS="da=38;5;245:sn=38;5;245:sb=38;5;245:uu=38;5;245"
alias ls="exa -am --group-directories-first --sort=name"
alias la="ls -l"
alias ll="ls -1"

# vim
alias vim="nvim"

# NPM
alias nb="npm run build"
alias ns="npm run start"
alias nt="npm run test"
alias np="npm version patch && npm publish && git push origin master --tags"

# Print each PATH entry on a separate line
alias path="echo -e ${PATH//:/\\n}"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"

# My alias
alias me="cd ~/Projects"
alias work="cd ~/Noggin"
alias dotfiles="cd ~/Projects/dotfiles"
alias zshconf="vim $HOME/.zshrc"
alias vimconf="vim $HOME/.vimrc"
alias afl="alias-finder -l $1"
alias woman="tldr $1"
alias git="hub"
alias gist="hub gist"
alias today='vim $(date +%d-%m-%Y).md'

